### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by jgowdy** [jankais3r/jankais3r#1]
https://raw.githubusercontent.com/jankais3r/Synology-Safe-Access-domain-list/master/adult.txt contains our corporate VPN endpoint hostnames:

ams3.secureserver.net
iad2.secureserver.net
phx3.secureserver.net
sin3.secureserver.net

There is no pornography there that I'm aware of.  Would you be able to de-list our hostnames?  Thanks.

**Comment by jankais3r** [comment]
Hi, thank you for flagging this, but this repository only serves as a mirror of Synology's list. If you want to have this entry removed, I recommend contacting them directly.
